spring:
    datasource:
        url: jdbc:sqlserver://isutacos.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
        username: isutacos
        password: Thisisourdatabase!
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
server:
    port: 8080

